api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        cache_headers:
            max_age: 60
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
